### ISSUE TITLE
Steam data is 72-86% matched, returns diminish

### ISSUE THREAD

**Issue by aaaaalbert** [mas-ude/cost-of-cloud-gaming#1]
Depending on the metric, we can match 72% (titles) to 85% (total players) of the Steam data with the Metacritic and HowLongToBeat datasets. This leaves us with a list of ~2,000 titles that (a) need manual matching or (b) won't match anything anyway.

Benevolent First Author For Lifetime @fmetzger decreed that it would make more sense to look at the PSnow and GeForceNow datasets next and make sure to put manual matching effort into their ~70 and ~250 titles first. So let's put further Steam data merging efforts on hold unless inspiration strikes.

---

Summarizing what I found out and/or did on top of @svenjaschroeder's merging work:
- The capitalization of titles isn't uniform across data sets. `tolower` helps.
- Steam titles include Unicode accents, quotation marks, (R), (TM), accented characters, ... : \342\204\242 , \342\200\230 , \342\200\231 , \302\256 , \303\247 , \303\251 , \303\240 ,\303\264 , \344\272\224\346\234\210\350\214\211\350\216\211 , \303\273 , \303\243 , \344\270\211\345\234\213\345\277\22713 , \343\203\226\343\203\253\343\203\274\343\203\240\343\203\274\343\203\263 , \302\262
- _However_, only 50 or so titles have Unicode chars in them. I didn't bother fixing them manually (for a meager 0.3% points increase in coverage).

A few quick stats on title matches, case-insensitive matches, and total players:

``` R
# Counting titles that match
moartitles <- c(df.metacritic$title, df.hltb$title)
dim(df.steamdata)  # 7749 rows, i.e. titles
length(setdiff(df.steamdata$name, moartitles))   # 2086 (misses 27% of titles)
length(setdiff(tolower(df.steamdata$name), tolower(moartitles)))  # 1840 (misses 24% of case-insensitive titles)

# Counting players
sum(df.steamdata$players_forever)   # 1071854903
sum(df.steamdata[df.steamdata$name %in% moartitles,]$players_forever)   # 887390337 (covers 82% of players)
sum(df.steamdata[tolower(df.steamdata$name) %in% tolower(moartitles),]$players_forever)    # 931261005  (covers 86% of players)
```

**Comment by aaaaalbert** [comment]
BTW, coverage is similar (81-85%) for _owners_ of games:

``` R
sum(df.steamdata$owners)   # 1690149633
sum(df.steamdata[(df.steamdata$name) %in% (moartitles),]$owners)   # 1373823250 (covers 81% of owners)
sum(df.steamdata[tolower(df.steamdata$name) %in% tolower(moartitles),]$owners)   # 1436680183 (covers 85% of owners)
```

**Comment by eliotou** [comment]
Hi!
I have received this e-mail! Maybe you have added me by mistake to this
list?
Cheers,
Eirini

**Comment by aaaaalbert** [comment]
Hi Eirini, you are on the [list of "watchers"](https://github.com/mas-ude/cost-of-cloud-gaming/watchers) of this repository, resulting in emails when there is activity. If you log into GitHub, you can follow that link and click on "Unwatch" to stop receiving notifications. Best, Albert.

**Comment by aaaaalbert** [comment]
...and yet another quick stat: The distributions of players and owners are similar for matched and unmatched records:

``` R
# `fivenum` yields the 0th, 25th, 50th, 75th and 100th percentile
fivenum((df.steamdata$players_forever))
#      0     1780     9408    51997 58666968
fivenum((df.steamdata[tolower(df.steamdata$name) %in% tolower(moartitles),]$players_forever))
#      0     2416    11188    61913 58666968
fivenum((df.steamdata$owners))
#      0     4831    21740   107299 58666968
fivenum((df.steamdata[tolower(df.steamdata$name) %in% tolower(moartitles),]$owners))
#  380.0     6357.0    25172.0   122173.5 58666968.0

```

**Comment by aaaaalbert** [comment]
``` R
yetmoartitles <- c(tolower(moartitles), tolower(df.steamdata$name))
# PSnow:
setdiff(tolower(df.psnow$Title), yetmoartitles)
# Two items only: "god of war ii hd", "greg hastings paintball"

# GFnow:
setdiff(tolower(df.gfnow$name), yetmoartitles)
# [1] "pumped bmx"                         
# [2] "the vanishing of ethan carter redux"
# [3] "killer is dead - nightmare edition" 
# [4] "the witcher 2: assassin of kings"   
# [5] "devil may cray 4"                   
# [6] "lego batman"                        
# [7] "lego batman 2 dc super heroes"      
# [8] "mx vs atv reflex"                   
# [9] "risen 2 dark waters"                
#[10] "streght fighter x tekken"           
```

**Comment by aaaaalbert** [comment]
# PSnow
- "God of War II HD" is probably HLTB's "God of War II" for PlayStation 3. (HLTB has a PS2 version too. Not HD I guess?)
- "Greg Hastings Paintball" in our list is "Greg Hastings Paintball _2_" [on the PSnow rentals page](https://www.playstation.com/en-us/explore/psnow/rentals/), and [exists for PS3 under the latter name](https://www.playstation.com/en-us/games/greg-hastings-paintball-2-ps3/)

# GFnow
- "Pumped BMX" could be Metacritic's "Pumped BMX +" for PS3, or Steam's of the same name. ~Almost matches for iOS: "Pumped: BMX", or "Pumped BMX 2".~
- "Killer is Dead - Nightmare Edition" matches Metacritic's "Killer Is Dead: Nightmare Edition" for PC.
- "The Witcher 2: Assassin of Kings" is "The Witcher 2: Assassin_s_ of Kings" in other datasets.
- "Devil May Cray 4" is a Freudian slip for "Devil May Cry 4" in other datasets.
- "Lego Batman" probably is "Lego Batman: The Videogame" for PC.
- "LEGO Batman 2 DC Super Heroes" needs a colon: "LEGO Batman 2: DC Super Heroes"
- "MX vs ATV Reflex" is "MX vs. ATV Reflex" (with an added dot)
- "Risen 2 Dark Waters" has alternative renditions "Risen 2: Dark Waters" and "Risen 2 - Dark Waters"
- "Streght Fighter X Tekken" is "Street Fighter X Tekken".

Alas,
- ["The Vanishing of Ethan Carter Redux"](https://shield.nvidia.com/games/geforce-now/the-vanishing-of-ethan-carter-redux) has no meaningful matches, but a recent mention on [Steam Community](http://steamcommunity.com/app/400430) which I can't find on steampowered.com; GFnow and the other data sets have a [non-redux version too](https://shield.nvidia.com/games/geforce-now/the-vanishing-of-ethan-carter).

---

If you think this makes sense, I can patch up the data source files.

**Comment by fmetzger** [comment]
> "God of War II HD" is probably HLTB's "God of War II" for PlayStation 3. (HLTB has a PS2 version too. Not HD I guess?)

Should be the PS3 one. 
Unfortunately, the list of PS Now titles also grew by about 150 since i last imported them. So these have to be added as well. However, we need to differentiate between the UK and the US service. I would like to focus on an European perspective, but the information is even more scarce for the UK service.
 Also, there is no public information (so far I can see) if the individual titles are included in the subscription or if they are rentals. The most info might be on the [wiki page](https://en.wikipedia.org/wiki/List_of_PlayStation_Now_games), but again probably US. The [official uk list](https://www.playstation.com/en-gb/explore/playstation-now/ps-now-games/) seems just grossly incomplete.

> "The Vanishing of Ethan Carter Redux" has no meaningful matches, but a recent mention on Steam Community which I can't find on steampowered.com; GFnow and the other data sets have a non-redux version too.

That game was a PC title first. When it got ported to PS4 they switched the engine to UE4, where it was released under the same, original, name. However, the new engine version was then also made available to owners of the original PC game under the Redux name. So: same game, different engine/releases and quite a few graphical differences.

**Comment by aaaaalbert** [comment]
I've just updated the GFnow (3433a8e48b746fbd6d82886994b2ff37eb11fad7) and PSnow (8c60994) datasets. I didn't edit "Ethan Carter Redux" though.

**Comment by aaaaalbert** [comment]
...but Florian did, and fixed lots of other issues too. Closing!
