### ISSUE TITLE
Remarks on the questionnarie

### ISSUE THREAD

**Issue by surminski** [mas-ude/cost-of-cloud-gaming#13]
I'd suggest to add an option that is not Nintendo-only to the answer 'System exclusive games (e.g. Zelda, Super Mario)' of the question 'What are for you the most important factors for buying a new gaming system?', for example Halo or Gran Turismo.

**Comment by svenjaschroeder** [comment]
Good idea! Unfortunately I didn't know of any other exclusive franchises. I'll add Halo and Gran Turismo. :-)

**Comment by fmetzger** [comment]
E.g. https://en.wikipedia.org/wiki/List_of_best-selling_video_game_franchises

**Comment by aaaaalbert** [comment]
Implemented in 9497d5d84ae31439a5ecbbbe539a1a0cd0b2ed62, and part of the live questionnaire in 7055c9f57167ef36864b7eadf6446490f14a22fa. Thanks for your comment, @surminski!
