### ISSUE TITLE
Proposal: Queueily recast "efficiency modelling"

### ISSUE THREAD

**Issue by aaaaalbert** [mas-ude/cost-of-cloud-gaming#2]
_Disclaimer: I'm not familiar with demand modelling so please forgive (and flame!) me if my observation is besides the point._

I think I get where the supply-side efficiency model is going, but my feeling is that the mathematical formulation / notation is slightly unconventional.
- $\epsilon$ is usually a positive number very close to 0 (cf. "epsilon neighborhood"). The overbooking coefficient should use a different letter.
- Capacity, overbooking, number of simultaneous users feel like they could be formulated in (reciprocal) terms of Little's law or the definition of _load_ as the quotient of _arrival rate_ and _service rate_, $\rho=\lambda / \mu$.

Your opinions?

**Comment by pzwickl** [comment]
The trick of the model is, from my point of view, how it represents things – which reduces the complexity substantially. The notion is, however, not final – I only see greek letters, which have almost infinite expression power. Nevertheless, I agree that analogies could be used to support the creation of a mental model.

The analogy to Little's law works (we have a model simplification here that ignores per-game and per-usage differences), but it's not identical. Could we draw from commonly used capacity overbooking symbols?

Apart from this, I also think that the _max and _min notions are partly counterintuitive (while they express the range, they positively relate to one case and negatively to the other). I might also reconsider this.

Thanks :)

**Comment by aaaaalbert** [comment]
Introduced by @pzwickl, found to not make the statement any stronger by me, removed in 1c9ca214274fe1519e506a46ee64c4e7049a508a. Sorry for proposing this in the first place.
