### ISSUE TITLE
Dichotomy of platforms: "cloud gaming" vs. "à la carte"/"sales-based"/"traditional"

### ISSUE THREAD

**Issue by svenjaschroeder** [mas-ude/cost-of-cloud-gaming#5]
I just edited the term "sales-based" into the abstract, but later in the introduction the traditional platforms are described as "à la carte". Which dichotomy of words do we want to use to describe both types of platforms we're looking at?

**Comment by aaaaalbert** [comment]
§ IV B "Cost-benefit model" uses "ownership model of STEAM, the hybrid subscription plus permanent rental model of GEFORCE NOW, as well as the subscription and timed rental model of PLAYSTATION NOW."

I used "à la carte" and "subscription-based" in § III iirc.

"Sales-based" might be too indifferent a qualifier, given that all of the platforms sell something (be it a game, or access to a game.)

**Comment by aaaaalbert** [comment]
In the current version of the paper, cloud gaming is further split into "Gaming as as Service" and "cloud rendering". I think I removed "sales-based", or it's not as prevalent as it was earlier, and same for "à la carte".

The current wording is "digital software distribution platforms" vs "cloud gaming".
