### ISSUE TITLE
too many cases of 'we'

### ISSUE THREAD

**Issue by fmetzger** [mas-ude/cost-of-cloud-gaming#8]
Most of the work is written in passive and 3rd person, but some cases of 'we' crept in. We should sanitize this (I already fixed some, but not all).

**Comment by aaaaalbert** [comment]
@fmetzger: PLX `push`!

**Comment by aaaaalbert** [comment]
Does f3a94fea1f2d6c4d4d5e42687faace47058c7c9e raise an `ENOTENOUGH` with you?

**Comment by aaaaalbert** [comment]
I declare this issue vanished.
